export enum SoundType {
  BLACK = "black",
  WHITE = "white",
  ONAJIKU = "同",
  ONE_ONE = "１ー",
  ONE_TWO = "１二",
  ONE_THREE = "１三",
  ONE_FOUR = "１四",
  ONE_FIVE = "１五",
  ONE_SIX = "１六",
  ONE_SEVEN = "１七",
  ONE_EIGHT = "１八",
  ONE_NINE = "１九",
  TWO_ONE = "２一",
  TWO_TWO = "２二",
  TWO_THREE = "２三",
  TWO_FOUR = "２四",
  TWO_FIVE = "２五",
  TWO_SIX = "２六",
  TWO_SEVEN = "２七",
  TWO_EIGHT = "２八",
  TWO_NINE = "２九",
  THREE_ONE = "３一",
  THREE_TWO = "３二",
  THREE_THREE = "３三",
  THREE_FOUR = "３四",
  THREE_FIVE = "３五",
  THREE_SIX = "３六",
  THREE_SEVEN = "３七",
  THREE_EIGHT = "３八",
  THREE_NINE = "３九",
  FOUR_ONE = "４一",
  FOUR_TWO = "４二",
  FOUR_THREE = "４三",
  FOUR_FOUR = "４四",
  FOUR_FIVE = "４五",
  FOUR_SIX = "４六",
  FOUR_SEVEN = "４七",
  FOUR_EIGHT = "４八",
  FOUR_NINE = "４九",
  FIVE_ONE = "５一",
  FIVE_TWO = "５二",
  FIVE_THREE = "５三",
  FIVE_FOUR = "５四",
  FIVE_FIVE = "５五",
  FIVE_SIX = "５六",
  FIVE_SEVEN = "５七",
  FIVE_EIGHT = "５八",
  FIVE_NINE = "５九",
  SIX_ONE = "６一",
  SIX_TWO = "６二",
  SIX_THREE = "６三",
  SIX_FOUR = "６四",
  SIX_FIVE = "６五",
  SIX_SIX = "６六",
  SIX_SEVEN = "６七",
  SIX_EIGHT = "６八",
  SIX_NINE = "６九",
  SEVEN_ONE = "７一",
  SEVEN_TWO = "７二",
  SEVEN_THREE = "７三",
  SEVEN_FOUR = "７四",
  SEVEN_FIVE = "７五",
  SEVEN_SIX = "７六",
  SEVEN_SEVEN = "７七",
  SEVEN_EIGHT = "７八",
  SEVEN_NINE = "７九",
  EIGHT_ONE = "８一",
  EIGHT_TWO = "８二",
  EIGHT_THREE = "８三",
  EIGHT_FOUR = "８四",
  EIGHT_FIVE = "８五",
  EIGHT_SIX = "８六",
  EIGHT_SEVEN = "８七",
  EIGHT_EIGHT = "８八",
  EIGHT_NINE = "８九",
  NINE_ONE = "９一",
  NINE_TWO = "９二",
  NINE_THREE = "９三",
  NINE_FOUR = "９四",
  NINE_FIVE = "９五",
  NINE_SIX = "９六",
  NINE_SEVEN = "９七",
  NINE_EIGHT = "９八",
  NINE_NINE = "９九",
  FU = "歩",
  KYO = "香",
  KEI = "桂",
  GIN = "銀",
  KIN = "金",
  HISHA = "飛",
  KAKU = "角",
  GYOKU = "玉",
  OU = "王",
  TOKIN = "と",
  NARIKYO = "成香",
  NARIKEI = "成桂",
  NARIGIN = "成銀",
  RYU = "龍",
  UMA = "馬",
  MIGI = "migi",
  HIDARI = "hidari",
  SUGU = "sugu",
  AGARU = "agaru",
  YORU = "yoru",
  HIKU = "hiku",
  NARU = "成",
  NARAZU = "不成",
  UTU = "utu",
  IKU = "iku",
  MADE = "made",
  FIRST_WIN = "first_win",
  SECOND_WIN = "second_win",
  SENNICHITEI = "sennichitei",
  JISYOGI = "jisyogi",
}

export const soundSourceMap = {
  [SoundType.BLACK]: "sound/machi/0.wav",
  [SoundType.WHITE]: "sound/machi/1.wav",
  [SoundType.ONAJIKU]: "sound/machi/00.wav",
  [SoundType.ONE_ONE]: "sound/machi/11.wav",
  [SoundType.ONE_TWO]: "sound/machi/12.wav",
  [SoundType.ONE_THREE]: "sound/machi/13.wav",
  [SoundType.ONE_FOUR]: "sound/machi/14.wav",
  [SoundType.ONE_FIVE]: "sound/machi/15.wav",
  [SoundType.ONE_SIX]: "sound/machi/16.wav",
  [SoundType.ONE_SEVEN]: "sound/machi/17.wav",
  [SoundType.ONE_EIGHT]: "sound/machi/18.wav",
  [SoundType.ONE_NINE]: "sound/machi/19.wav",
  [SoundType.TWO_ONE]: "sound/machi/21.wav",
  [SoundType.TWO_TWO]: "sound/machi/22.wav",
  [SoundType.TWO_THREE]: "sound/machi/23.wav",
  [SoundType.TWO_FOUR]: "sound/machi/24.wav",
  [SoundType.TWO_FIVE]: "sound/machi/25.wav",
  [SoundType.TWO_SIX]: "sound/machi/26.wav",
  [SoundType.TWO_SEVEN]: "sound/machi/27.wav",
  [SoundType.TWO_EIGHT]: "sound/machi/28.wav",
  [SoundType.TWO_NINE]: "sound/machi/29.wav",
  [SoundType.THREE_ONE]: "sound/machi/31.wav",
  [SoundType.THREE_TWO]: "sound/machi/32.wav",
  [SoundType.THREE_THREE]: "sound/machi/33.wav",
  [SoundType.THREE_FOUR]: "sound/machi/34.wav",
  [SoundType.THREE_FIVE]: "sound/machi/35.wav",
  [SoundType.THREE_SIX]: "sound/machi/36.wav",
  [SoundType.THREE_SEVEN]: "sound/machi/37.wav",
  [SoundType.THREE_EIGHT]: "sound/machi/38.wav",
  [SoundType.THREE_NINE]: "sound/machi/39.wav",
  [SoundType.FOUR_ONE]: "sound/machi/41.wav",
  [SoundType.FOUR_TWO]: "sound/machi/42.wav",
  [SoundType.FOUR_THREE]: "sound/machi/43.wav",
  [SoundType.FOUR_FOUR]: "sound/machi/44.wav",
  [SoundType.FOUR_FIVE]: "sound/machi/45.wav",
  [SoundType.FOUR_SIX]: "sound/machi/46.wav",
  [SoundType.FOUR_SEVEN]: "sound/machi/47.wav",
  [SoundType.FOUR_EIGHT]: "sound/machi/48.wav",
  [SoundType.FOUR_NINE]: "sound/machi/49.wav",
  [SoundType.FIVE_ONE]: "sound/machi/51.wav",
  [SoundType.FIVE_TWO]: "sound/machi/52.wav",
  [SoundType.FIVE_THREE]: "sound/machi/53.wav",
  [SoundType.FIVE_FOUR]: "sound/machi/54.wav",
  [SoundType.FIVE_FIVE]: "sound/machi/55.wav",
  [SoundType.FIVE_SIX]: "sound/machi/56.wav",
  [SoundType.FIVE_SEVEN]: "sound/machi/57.wav",
  [SoundType.FIVE_EIGHT]: "sound/machi/58.wav",
  [SoundType.FIVE_NINE]: "sound/machi/59.wav",
  [SoundType.SIX_ONE]: "sound/machi/61.wav",
  [SoundType.SIX_TWO]: "sound/machi/62.wav",
  [SoundType.SIX_THREE]: "sound/machi/63.wav",
  [SoundType.SIX_FOUR]: "sound/machi/64.wav",
  [SoundType.SIX_FIVE]: "sound/machi/65.wav",
  [SoundType.SIX_SIX]: "sound/machi/66.wav",
  [SoundType.SIX_SEVEN]: "sound/machi/67.wav",
  [SoundType.SIX_EIGHT]: "sound/machi/68.wav",
  [SoundType.SIX_NINE]: "sound/machi/69.wav",
  [SoundType.SEVEN_ONE]: "sound/machi/71.wav",
  [SoundType.SEVEN_TWO]: "sound/machi/72.wav",
  [SoundType.SEVEN_THREE]: "sound/machi/73.wav",
  [SoundType.SEVEN_FOUR]: "sound/machi/74.wav",
  [SoundType.SEVEN_FIVE]: "sound/machi/75.wav",
  [SoundType.SEVEN_SIX]: "sound/machi/76.wav",
  [SoundType.SEVEN_SEVEN]: "sound/machi/77.wav",
  [SoundType.SEVEN_EIGHT]: "sound/machi/78.wav",
  [SoundType.SEVEN_NINE]: "sound/machi/79.wav",
  [SoundType.EIGHT_ONE]: "sound/machi/81.wav",
  [SoundType.EIGHT_TWO]: "sound/machi/82.wav",
  [SoundType.EIGHT_THREE]: "sound/machi/83.wav",
  [SoundType.EIGHT_FOUR]: "sound/machi/84.wav",
  [SoundType.EIGHT_FIVE]: "sound/machi/85.wav",
  [SoundType.EIGHT_SIX]: "sound/machi/86.wav",
  [SoundType.EIGHT_SEVEN]: "sound/machi/87.wav",
  [SoundType.EIGHT_EIGHT]: "sound/machi/88.wav",
  [SoundType.EIGHT_NINE]: "sound/machi/89.wav",
  [SoundType.NINE_ONE]: "sound/machi/91.wav",
  [SoundType.NINE_TWO]: "sound/machi/92.wav",
  [SoundType.NINE_THREE]: "sound/machi/93.wav",
  [SoundType.NINE_FOUR]: "sound/machi/94.wav",
  [SoundType.NINE_FIVE]: "sound/machi/95.wav",
  [SoundType.NINE_SIX]: "sound/machi/96.wav",
  [SoundType.NINE_SEVEN]: "sound/machi/97.wav",
  [SoundType.NINE_EIGHT]: "sound/machi/98.wav",
  [SoundType.NINE_NINE]: "sound/machi/99.wav",

  [SoundType.FU]: "sound/machi/101.wav",
  [SoundType.KYO]: "sound/machi/102.wav",
  [SoundType.KEI]: "sound/machi/103.wav",
  [SoundType.GIN]: "sound/machi/104.wav",
  [SoundType.KIN]: "sound/machi/105.wav",
  [SoundType.HISHA]: "sound/machi/106.wav",
  [SoundType.KAKU]: "sound/machi/107.wav",
  [SoundType.GYOKU]: "sound/machi/108.wav",
  [SoundType.OU]: "sound/machi/109.wav",
  [SoundType.TOKIN]: "sound/machi/111.wav",
  [SoundType.NARIKYO]: "sound/machi/112.wav",
  [SoundType.NARIKEI]: "sound/machi/113.wav",
  [SoundType.NARIGIN]: "sound/machi/114.wav",
  [SoundType.RYU]: "sound/machi/116.wav",
  [SoundType.UMA]: "sound/machi/117.wav",
  [SoundType.MIGI]: "sound/machi/201.wav",
  [SoundType.HIDARI]: "sound/machi/202.wav",
  [SoundType.SUGU]: "sound/machi/203.wav",
  [SoundType.AGARU]: "sound/machi/204.wav",
  [SoundType.YORU]: "sound/machi/205.wav",
  [SoundType.HIKU]: "sound/machi/206.wav",
  [SoundType.NARU]: "sound/machi/207.wav",
  [SoundType.NARAZU]: "sound/machi/208.wav",
  [SoundType.UTU]: "sound/machi/209.wav",
  [SoundType.IKU]: "sound/machi/210.wav",
  [SoundType.MADE]: "sound/machi/301.wav",
  [SoundType.FIRST_WIN]: "sound/machi/302.wav",
  [SoundType.SECOND_WIN]: "sound/machi/303.wav",
  [SoundType.SENNICHITEI]: "sound/machi/304.wav",
  [SoundType.JISYOGI]: "sound/machi/305.wav",
};
