const SOUND_DIR = "machi";

export enum SoundType {
  BLACK = "black",
  WHITE = "white",
  ONAJIKU = "同",
  ONE_ONE = "11",
  ONE_TWO = "12",
  ONE_THREE = "13",
  ONE_FOUR = "14",
  ONE_FIVE = "15",
  ONE_SIX = "16",
  ONE_SEVEN = "17",
  ONE_EIGHT = "18",
  ONE_NINE = "19",
  TWO_ONE = "21",
  TWO_TWO = "22",
  TWO_THREE = "23",
  TWO_FOUR = "24",
  TWO_FIVE = "25",
  TWO_SIX = "26",
  TWO_SEVEN = "27",
  TWO_EIGHT = "28",
  TWO_NINE = "29",
  THREE_ONE = "31",
  THREE_TWO = "32",
  THREE_THREE = "33",
  THREE_FOUR = "34",
  THREE_FIVE = "35",
  THREE_SIX = "36",
  THREE_SEVEN = "37",
  THREE_EIGHT = "38",
  THREE_NINE = "39",
  FOUR_ONE = "41",
  FOUR_TWO = "42",
  FOUR_THREE = "43",
  FOUR_FOUR = "44",
  FOUR_FIVE = "45",
  FOUR_SIX = "46",
  FOUR_SEVEN = "47",
  FOUR_EIGHT = "48",
  FOUR_NINE = "49",
  FIVE_ONE = "51",
  FIVE_TWO = "52",
  FIVE_THREE = "53",
  FIVE_FOUR = "54",
  FIVE_FIVE = "55",
  FIVE_SIX = "56",
  FIVE_SEVEN = "57",
  FIVE_EIGHT = "58",
  FIVE_NINE = "59",
  SIX_ONE = "61",
  SIX_TWO = "62",
  SIX_THREE = "63",
  SIX_FOUR = "64",
  SIX_FIVE = "65",
  SIX_SIX = "66",
  SIX_SEVEN = "67",
  SIX_EIGHT = "68",
  SIX_NINE = "69",
  SEVEN_ONE = "71",
  SEVEN_TWO = "72",
  SEVEN_THREE = "73",
  SEVEN_FOUR = "74",
  SEVEN_FIVE = "75",
  SEVEN_SIX = "76",
  SEVEN_SEVEN = "77",
  SEVEN_EIGHT = "78",
  SEVEN_NINE = "79",
  EIGHT_ONE = "81",
  EIGHT_TWO = "82",
  EIGHT_THREE = "83",
  EIGHT_FOUR = "84",
  EIGHT_FIVE = "85",
  EIGHT_SIX = "86",
  EIGHT_SEVEN = "87",
  EIGHT_EIGHT = "88",
  EIGHT_NINE = "89",
  NINE_ONE = "91",
  NINE_TWO = "92",
  NINE_THREE = "93",
  NINE_FOUR = "94",
  NINE_FIVE = "95",
  NINE_SIX = "96",
  NINE_SEVEN = "97",
  NINE_EIGHT = "98",
  NINE_NINE = "99",
  FU = "歩",
  KYO = "香",
  KEI = "桂",
  GIN = "銀",
  KIN = "金",
  HISHA = "飛",
  KAKU = "角",
  GYOKU = "玉",
  OU = "王",
  TOKIN = "と",
  NARIKYO = "成香",
  NARIKEI = "成桂",
  NARIGIN = "成銀",
  RYU = "龍",
  UMA = "馬",
  MIGI = "migi",
  HIDARI = "hidari",
  SUGU = "sugu",
  AGARU = "agaru",
  YORU = "yoru",
  HIKU = "hiku",
  NARU = "成",
  NARAZU = "不成",
  UTU = "utu",
  IKU = "iku",
  MADE = "made",
  BLACK_WIN = "black_win",
  WHITE_WIN = "white_win",
  SENNICHITEI = "sennichitei",
  JISYOGI = "jisyogi",
}

export const soundSourceMap = {
  [SoundType.BLACK]: `sound/${SOUND_DIR}/0.wav`,
  [SoundType.WHITE]: `sound/${SOUND_DIR}/1.wav`,
  [SoundType.ONAJIKU]: `sound/${SOUND_DIR}/00.wav`,
  [SoundType.ONE_ONE]: `sound/${SOUND_DIR}/11.wav`,
  [SoundType.ONE_TWO]: `sound/${SOUND_DIR}/12.wav`,
  [SoundType.ONE_THREE]: `sound/${SOUND_DIR}/13.wav`,
  [SoundType.ONE_FOUR]: `sound/${SOUND_DIR}/14.wav`,
  [SoundType.ONE_FIVE]: `sound/${SOUND_DIR}/15.wav`,
  [SoundType.ONE_SIX]: `sound/${SOUND_DIR}/16.wav`,
  [SoundType.ONE_SEVEN]: `sound/${SOUND_DIR}/17.wav`,
  [SoundType.ONE_EIGHT]: `sound/${SOUND_DIR}/18.wav`,
  [SoundType.ONE_NINE]: `sound/${SOUND_DIR}/19.wav`,
  [SoundType.TWO_ONE]: `sound/${SOUND_DIR}/21.wav`,
  [SoundType.TWO_TWO]: `sound/${SOUND_DIR}/22.wav`,
  [SoundType.TWO_THREE]: `sound/${SOUND_DIR}/23.wav`,
  [SoundType.TWO_FOUR]: `sound/${SOUND_DIR}/24.wav`,
  [SoundType.TWO_FIVE]: `sound/${SOUND_DIR}/25.wav`,
  [SoundType.TWO_SIX]: `sound/${SOUND_DIR}/26.wav`,
  [SoundType.TWO_SEVEN]: `sound/${SOUND_DIR}/27.wav`,
  [SoundType.TWO_EIGHT]: `sound/${SOUND_DIR}/28.wav`,
  [SoundType.TWO_NINE]: `sound/${SOUND_DIR}/29.wav`,
  [SoundType.THREE_ONE]: `sound/${SOUND_DIR}/31.wav`,
  [SoundType.THREE_TWO]: `sound/${SOUND_DIR}/32.wav`,
  [SoundType.THREE_THREE]: `sound/${SOUND_DIR}/33.wav`,
  [SoundType.THREE_FOUR]: `sound/${SOUND_DIR}/34.wav`,
  [SoundType.THREE_FIVE]: `sound/${SOUND_DIR}/35.wav`,
  [SoundType.THREE_SIX]: `sound/${SOUND_DIR}/36.wav`,
  [SoundType.THREE_SEVEN]: `sound/${SOUND_DIR}/37.wav`,
  [SoundType.THREE_EIGHT]: `sound/${SOUND_DIR}/38.wav`,
  [SoundType.THREE_NINE]: `sound/${SOUND_DIR}/39.wav`,
  [SoundType.FOUR_ONE]: `sound/${SOUND_DIR}/41.wav`,
  [SoundType.FOUR_TWO]: `sound/${SOUND_DIR}/42.wav`,
  [SoundType.FOUR_THREE]: `sound/${SOUND_DIR}/43.wav`,
  [SoundType.FOUR_FOUR]: `sound/${SOUND_DIR}/44.wav`,
  [SoundType.FOUR_FIVE]: `sound/${SOUND_DIR}/45.wav`,
  [SoundType.FOUR_SIX]: `sound/${SOUND_DIR}/46.wav`,
  [SoundType.FOUR_SEVEN]: `sound/${SOUND_DIR}/47.wav`,
  [SoundType.FOUR_EIGHT]: `sound/${SOUND_DIR}/48.wav`,
  [SoundType.FOUR_NINE]: `sound/${SOUND_DIR}/49.wav`,
  [SoundType.FIVE_ONE]: `sound/${SOUND_DIR}/51.wav`,
  [SoundType.FIVE_TWO]: `sound/${SOUND_DIR}/52.wav`,
  [SoundType.FIVE_THREE]: `sound/${SOUND_DIR}/53.wav`,
  [SoundType.FIVE_FOUR]: `sound/${SOUND_DIR}/54.wav`,
  [SoundType.FIVE_FIVE]: `sound/${SOUND_DIR}/55.wav`,
  [SoundType.FIVE_SIX]: `sound/${SOUND_DIR}/56.wav`,
  [SoundType.FIVE_SEVEN]: `sound/${SOUND_DIR}/57.wav`,
  [SoundType.FIVE_EIGHT]: `sound/${SOUND_DIR}/58.wav`,
  [SoundType.FIVE_NINE]: `sound/${SOUND_DIR}/59.wav`,
  [SoundType.SIX_ONE]: `sound/${SOUND_DIR}/61.wav`,
  [SoundType.SIX_TWO]: `sound/${SOUND_DIR}/62.wav`,
  [SoundType.SIX_THREE]: `sound/${SOUND_DIR}/63.wav`,
  [SoundType.SIX_FOUR]: `sound/${SOUND_DIR}/64.wav`,
  [SoundType.SIX_FIVE]: `sound/${SOUND_DIR}/65.wav`,
  [SoundType.SIX_SIX]: `sound/${SOUND_DIR}/66.wav`,
  [SoundType.SIX_SEVEN]: `sound/${SOUND_DIR}/67.wav`,
  [SoundType.SIX_EIGHT]: `sound/${SOUND_DIR}/68.wav`,
  [SoundType.SIX_NINE]: `sound/${SOUND_DIR}/69.wav`,
  [SoundType.SEVEN_ONE]: `sound/${SOUND_DIR}/71.wav`,
  [SoundType.SEVEN_TWO]: `sound/${SOUND_DIR}/72.wav`,
  [SoundType.SEVEN_THREE]: `sound/${SOUND_DIR}/73.wav`,
  [SoundType.SEVEN_FOUR]: `sound/${SOUND_DIR}/74.wav`,
  [SoundType.SEVEN_FIVE]: `sound/${SOUND_DIR}/75.wav`,
  [SoundType.SEVEN_SIX]: `sound/${SOUND_DIR}/76.wav`,
  [SoundType.SEVEN_SEVEN]: `sound/${SOUND_DIR}/77.wav`,
  [SoundType.SEVEN_EIGHT]: `sound/${SOUND_DIR}/78.wav`,
  [SoundType.SEVEN_NINE]: `sound/${SOUND_DIR}/79.wav`,
  [SoundType.EIGHT_ONE]: `sound/${SOUND_DIR}/81.wav`,
  [SoundType.EIGHT_TWO]: `sound/${SOUND_DIR}/82.wav`,
  [SoundType.EIGHT_THREE]: `sound/${SOUND_DIR}/83.wav`,
  [SoundType.EIGHT_FOUR]: `sound/${SOUND_DIR}/84.wav`,
  [SoundType.EIGHT_FIVE]: `sound/${SOUND_DIR}/85.wav`,
  [SoundType.EIGHT_SIX]: `sound/${SOUND_DIR}/86.wav`,
  [SoundType.EIGHT_SEVEN]: `sound/${SOUND_DIR}/87.wav`,
  [SoundType.EIGHT_EIGHT]: `sound/${SOUND_DIR}/88.wav`,
  [SoundType.EIGHT_NINE]: `sound/${SOUND_DIR}/89.wav`,
  [SoundType.NINE_ONE]: `sound/${SOUND_DIR}/91.wav`,
  [SoundType.NINE_TWO]: `sound/${SOUND_DIR}/92.wav`,
  [SoundType.NINE_THREE]: `sound/${SOUND_DIR}/93.wav`,
  [SoundType.NINE_FOUR]: `sound/${SOUND_DIR}/94.wav`,
  [SoundType.NINE_FIVE]: `sound/${SOUND_DIR}/95.wav`,
  [SoundType.NINE_SIX]: `sound/${SOUND_DIR}/96.wav`,
  [SoundType.NINE_SEVEN]: `sound/${SOUND_DIR}/97.wav`,
  [SoundType.NINE_EIGHT]: `sound/${SOUND_DIR}/98.wav`,
  [SoundType.NINE_NINE]: `sound/${SOUND_DIR}/99.wav`,

  [SoundType.FU]: `sound/${SOUND_DIR}/101.wav`,
  [SoundType.KYO]: `sound/${SOUND_DIR}/102.wav`,
  [SoundType.KEI]: `sound/${SOUND_DIR}/103.wav`,
  [SoundType.GIN]: `sound/${SOUND_DIR}/104.wav`,
  [SoundType.KIN]: `sound/${SOUND_DIR}/105.wav`,
  [SoundType.HISHA]: `sound/${SOUND_DIR}/106.wav`,
  [SoundType.KAKU]: `sound/${SOUND_DIR}/107.wav`,
  [SoundType.GYOKU]: `sound/${SOUND_DIR}/108.wav`,
  [SoundType.OU]: `sound/${SOUND_DIR}/109.wav`,
  [SoundType.TOKIN]: `sound/${SOUND_DIR}/111.wav`,
  [SoundType.NARIKYO]: `sound/${SOUND_DIR}/112.wav`,
  [SoundType.NARIKEI]: `sound/${SOUND_DIR}/113.wav`,
  [SoundType.NARIGIN]: `sound/${SOUND_DIR}/114.wav`,
  [SoundType.RYU]: `sound/${SOUND_DIR}/116.wav`,
  [SoundType.UMA]: `sound/${SOUND_DIR}/117.wav`,
  [SoundType.MIGI]: `sound/${SOUND_DIR}/201.wav`,
  [SoundType.HIDARI]: `sound/${SOUND_DIR}/202.wav`,
  [SoundType.SUGU]: `sound/${SOUND_DIR}/203.wav`,
  [SoundType.AGARU]: `sound/${SOUND_DIR}/204.wav`,
  [SoundType.YORU]: `sound/${SOUND_DIR}/205.wav`,
  [SoundType.HIKU]: `sound/${SOUND_DIR}/206.wav`,
  [SoundType.NARU]: `sound/${SOUND_DIR}/207.wav`,
  [SoundType.NARAZU]: `sound/${SOUND_DIR}/208.wav`,
  [SoundType.UTU]: `sound/${SOUND_DIR}/209.wav`,
  [SoundType.IKU]: `sound/${SOUND_DIR}/210.wav`,
  [SoundType.MADE]: `sound/${SOUND_DIR}/301.wav`,
  [SoundType.BLACK_WIN]: `sound/${SOUND_DIR}/302.wav`,
  [SoundType.WHITE_WIN]: `sound/${SOUND_DIR}/303.wav`,
  [SoundType.SENNICHITEI]: `sound/${SOUND_DIR}/304.wav`,
  [SoundType.JISYOGI]: `sound/${SOUND_DIR}/305.wav`,
};
